{% set name = "opentelemetry-instrumentation-bedrock" %}
{% set version = "0.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 43f46f33b4b2117acabdd358cbb8af1647548575fad73b573d16115e593b39ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.55b0
    - opentelemetry-semantic-conventions >=0.55b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
    - anthropic >=0.17.0
    - tokenizers >=0.13.0
  run_constrained:
    - boto3 >=1.34.120,<2.0.0

# Unable to run the tests, opentelemetry-test-utils is not in the main channel. No module named 'opentelemetry.test'.
test:
  imports:
    - opentelemetry.instrumentation.bedrock
  commands:
    - pip check
  requires:
    - pip
    - boto3

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Bedrock instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
